// <auto-generated />
namespace pi.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class conversation12345678 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(conversation12345678));
        
        string IMigrationMetadata.Id
        {
            get { return "201911072030423_conversation12345678"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
