// <auto-generated />
namespace pi.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class conversation123456 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(conversation123456));
        
        string IMigrationMetadata.Id
        {
            get { return "201911072021260_conversation123456"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
